name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  java-version: '8'
  java-distribution: 'adopt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Cache outputs
        id: outputs-cache
        uses: actions/cache@v2
        with:
          path: |
            build
            app/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('app/src/**/*') }}
      - name: Build project
        if: steps.outputs-cache.outputs.cache-hit != 'true'
        run: |
          chmod 777 ./gradlew
          ./gradlew :app:build
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GRADLE_TOKEN }}
      - name: Cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  deploy:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-distribution }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Cache outputs
        uses: actions/cache@v2
        with:
          path: |
            build
            app/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('app/src/**/*') }}
      - name: Deploy project
        run: |
          chmod 777 ./gradlew
          ./gradlew :app:publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GRADLE_TOKEN }}
      - name: Cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
    needs: build
